[2024-03-16T00:47:02.952-0400] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: PII_Data_Detection.load_data_from_gcp manual__2024-03-15T04:39:01.247825+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
